[workspace]
description = "Mojo TLSE Bindings."
authors = ["Mikhail Tavarez <miktavarez@gmail.com>"]
channels = ["https://repo.prefix.dev/mojo-community", "conda-forge", "https://conda.modular.com/max", "https://prefix.dev/pixi-build-backends"]
platforms = ["osx-arm64", "linux-64"]
license = "MIT"
license-file = "LICENSE"
readme = "README.md"
homepage = "https://github.com/thatstoasty/mojo-tlse"
repository = "https://github.com/thatstoasty/mojo-tlse"
preview = ["pixi-build"]

[feature.util.tasks]
tests = "python scripts/util.py run-tests"
benchmarks = "python scripts/util.py run-benchmarks"
examples = "python scripts/util.py run-examples"
template = "python scripts/util.py generate-recipe"
build = { cmd = "python scripts/util.py build-conda-package" }
publish = { cmd = "python scripts/util.py publish", env = { PREFIX_API_KEY = "$PREFIX_API_KEY" } }

# Linting and Formatting
lint_docs = "python3 scripts/check-docstrings.py"
mojo_format = "mojo format mojo_tlse --line-length 120"
sort_imports = "isort **/*.mojo -m 3 --line-length 120 --lines-after-imports 2 --trailing-comma"
format = [{ task = "mojo_format" }, { task = "sort_imports" }]

[dependencies]
mojo = ">=25.5.0,<25.6.0"
mojo-compiler = ">=25.5.0,<25.6.0"

[package]
name = "mojo-tlse"
version = "25.5.0"

[package.build]
backend = { name = "pixi-build-rattler-build", version = "*" }

[feature.util.dependencies]
typer = ">=0.16.0,<0.17"
pyyaml = ">=6.0.2,<7"
isort = ">=6.0.1,<7"

[environments]
default = { solve-group = "default" }
util = { features = ["util"], solve-group = "default" }
