[project]
authors = ["Mikhail Tavarez <miktavarez@gmail.com>"]
channels = [
    "conda-forge",
    "https://conda.modular.com/max",
    "https://repo.prefix.dev/mojo-community",
    "file:///Users/mikhailtavarez/.rattler/output"
]
description = "Add a short description here"
name = "mojo-tlse-client"
platforms = ["osx-arm64"]
version = "0.1.0"

[dependencies]
max = "==24.6.0"
lightbug_http = "==0.1.10"
mojo-tlse = ">=0.1.2,<0.2"
