[project]
authors = ["Mikhail Tavarez <miktavarez@gmail.com>"]
channels = [
    "conda-forge",
    "https://conda.modular.com/max",
    "https://repo.prefix.dev/mojo-community",
]
description = "Add a short description here"
name = "mojo-tlse-client"
platforms = ["osx-arm64"]
version = "0.1.0"

[dependencies]
max = "==25.1.0"
lightbug_http = "==0.1.12"
mojo-tlse = "==25.1.0"
