[project]
authors = ["Mikhail Tavarez <miktavarez@gmail.com>"]
channels = [
    "conda-forge",
    "https://conda.modular.com/max",
    "https://repo.prefix.dev/mojo-community",
]
description = "Add a short description here"
name = "mojo-tlse-client"
platforms = ["osx-arm64", "linux-64", "linux-aarch64"]
version = "0.1.0"

[dependencies]
max = "=25.5.0"
lightbug_http = "=25.5.0"
mojo-tlse = "=25.5.0"
